# Generated by Django 4.2.17 on 2024-12-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacymanager',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pharmacymanager',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pharmacymanager',
            name='username',
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='first_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='last_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacymanager',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
