# Generated by Django 4.2.17 on 2024-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacymanager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='location',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
